package trab3_main;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import lib.NumberUtils;

/**
 *
 * @author Utilizador
 */
public class home extends javax.swing.JFrame {

    public home() {
        initComponents();
    }

    
    public static String generateRandomFloats(int count) {
        Random random = new Random();
        String result = "";
        
        for (int i = 0; i < count; i++) {
            // gera 1 numero inteiro aleatorio de 1 a 100
            int number = 1 + random.nextInt(100 - 1 + 1);
            
            // valida se é o primeiro numero, caso seja nao adicona a virgula antes do numero
            if (i == 0)
                result = result + number;
            else
                result = result + "," + number;
        }
               
        return result;
    }
    
    public static List<Double> convertToArrayList(String input) {
        List<Double> listNumbers = new ArrayList<>();
        
        try {
            // Remove espaço e dividir a string por vírgulas
            String[] parts = input.split("\\s*,\\s*");

            // Pega em cada bloco \\s* converte em double e adiciona à lista 
            for (String part : parts) {
                listNumbers.add(Double.valueOf(part));
            }
        } catch (Exception e) {
            // limpa a lista caso exista erro na listagem dos numeros
            listNumbers.clear();
            //listNumbers.add(Double.parseDouble("0"));
            System.out.println("Erro a carregar informação" + e.getMessage());
        }
 
        return listNumbers;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        txtNumbers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butGerar = new javax.swing.JButton();
        butCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        jLabel1.setText("Inserir os numeros separados por virgula (ex.: 10,2.5,5,8,9.5,2)");

        butGerar.setText("Gerar 10 Numeros");
        butGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGerarActionPerformed(evt);
            }
        });

        butCalcular.setText("Calcular");
        butCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtNumbers)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butGerar)
                    .addComponent(butCalcular))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGerarActionPerformed
        txtNumbers.setText(generateRandomFloats(10));
    }//GEN-LAST:event_butGerarActionPerformed

    private void butCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcularActionPerformed
        //List<Double> numeros = Arrays.asList(5.0, 3.0, 8.0, 1.0, 2.0, 5.0);  // lista de números.
        List<Double> numeros = convertToArrayList(txtNumbers.getText());
               
        //Limpa cx de informação
        txtResult.setText("");
        
        if (numeros.isEmpty()) {
            txtResult.append("Foram indicados numeros incorretamente \n\n");
        
        } else {
        // Teste da Média
        txtResult.append("Média: " + NumberUtils.calcularMedia(numeros) + "\n");
        
        // Teste da Médiana
        txtResult.append("Mediana: " + NumberUtils.calcularMediana(numeros) + "\n");
        
        // Teste da Moda
        txtResult.append("Moda: " + NumberUtils.calcularModa(numeros) + "\n");
        
        // Teste da Ordenação Crescente
        txtResult.append("Lista Ordenada Crescente: " + NumberUtils.ordenarLista(numeros, true) + "\n");
        
        // Teste da Ordenação Decrescente
        txtResult.append("Lista Ordenada Decrescente: " + NumberUtils.ordenarLista(numeros, false) + "\n");
        }
    }//GEN-LAST:event_butCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCalcular;
    private javax.swing.JButton butGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumbers;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
